#
# Copyright (C) 2016 Urchinly <wabi-sabi@urchinly.uk>
#

version: "2"

services:
  events:
    image: urchinly/sabi-events
    environment:
     - SPRING_PROFILES_ACTIVE=prod
     - SPRING_RABBITMQ_ADDRESSES=wabi_rabbitmq_1,wabi_rabbitmq_2,wabi_rabbitmq_3
    ports:
     - "7081:7081"
    volumes:
     - /tmp

  mailer:
    image: urchinly/sabi-mailer
    environment:
     - SPRING_PROFILES_ACTIVE=prod
     - SPRING_RABBITMQ_ADDRESSES=wabi_rabbitmq_1,wabi_rabbitmq_2,wabi_rabbitmq_3
    ports:
     - "7082:7082"
    volumes:
     - /tmp
